<?xml version="1.0"?>
<robot name="pinky" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>
    
    <xacro:property name="meshes_file_direction" value="file://$(find robot_description)/meshes"/>

    <xacro:property name="actuator_height" value="0.061"/>
    <xacro:property name="actuator_diameter" value="0.065"/>
    <xacro:property name="actuator_radius" value="${actuator_diameter / 2}"/>
    <xacro:property name="actuator_mass" value="0.350"/>
    <xacro:property name="actuator_width" value="0.065"/>
    
    <xacro:property name="upperarm_width" value="0.065"/>
    <xacro:property name="upperarm_length" value="0.270"/>
    <xacro:property name="upperarm_mass" value="0.300"/>

    <xacro:property name="forearm_width" value="0.065"/>
    <xacro:property name="forearm_length" value="0.185"/>
    <xacro:property name="forearm_mass" value="0.176"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="grey">
        <color rgba="0.2 0.2 0.2 1"/>
    </material>

    <link name="base_footprint"/>

    <joint name="base_link_fixed_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="arm_base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="arm_base_link"/>
    
    <joint name="actuator1_to_base_link" type="fixed">
        <parent link="arm_base_link"/>
        <child link="actuator1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>

    </joint>

    <link name="actuator1">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator1.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator1.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${actuator_mass}" radius="${actuator_radius}" 
                                 length="${actuator_height}">
            <origin xyz="0 0 ${actuator_height/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="actuator2_to_actuator1" type="revolute">
        <parent link="actuator1"/>
        <child link="actuator2"/>
        <origin xyz="0 0 0.06" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="100"/>
        <dynamics damping="0.1"/>
    </joint>
    
    <link name="actuator2">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator2.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual> 
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator2.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${actuator_mass}" x="${actuator_width}" y="${actuator_width}" z="${actuator_width}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="upperarm_link_to_actuator2" type="revolute">
        <parent link="actuator2"/>
        <child link="upperarm_link"/>
        <origin xyz="0 ${actuator_width/2} 0.0835" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-1.57" upper="1.57" effort="100" velocity="100"/>
        <dynamics damping="0.1"/>
    </joint>
        
    <link name="upperarm_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/upperarm_link.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/upperarm_link.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${upperarm_mass}" x="${upperarm_width}" y="${upperarm_width}" z="${upperarm_length}">
            <origin xyz="0 0 ${(upperarm_length - upperarm_width)/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="actuator3_to_upperarm_link" type="revolute">
        <parent link="upperarm_link"/>
        <child link="actuator3"/>
        <origin xyz="0 0 0.215" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-1.57" upper="1.57" effort="100" velocity="100"/>
        <dynamics damping="0.1"/>
    </joint>

    <link name="actuator3">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator3.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator3.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${actuator_mass}" x="${actuator_width}" y="${actuator_width}" z="${actuator_width}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="forearm_link_to_actuator3" type="fixed">
        <parent link="actuator3"/>
        <child link="forearm_link"/>
        <origin xyz="0 ${-actuator_width/2} ${actuator_width/2}" rpy="0 0 0"/>
    </joint>

    <link name="forearm_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/forearm_link.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/forearm_link.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${forearm_mass}" x="${forearm_width}" y="${forearm_width}" z="${forearm_length}">
            <origin xyz="0 0 ${forearm_length / 2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="actuator4_to_forearm_link" type="revolute">
        <parent link="forearm_link"/>
        <child link="actuator4"/>
        <origin xyz="0 0 0.170" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="100"/>
        <dynamics damping="0.1"/>
    </joint>

    <link name="actuator4">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator4.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${actuator_width/2}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator4.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${actuator_mass}" x="${actuator_width}" y="${actuator_width}" z="${actuator_width}">
            <origin xyz="0 0 ${actuator_width/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="gripper_base_fixed" type="fixed">
        <parent link="actuator4"/>
        <child link="gripper_base"/>
        <origin xyz="0 0 ${actuator_width/2}" rpy="0 -1.5707 0"/>
    </joint>

    <link name="gripper_base">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link5.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link5.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.160" x="0.08" y="0.05" z="0.04">
            <origin xyz="0.04 0 0" rpy="0 0 0"/> 
        </xacro:inertial_box>
    </link>

    <joint name="gripper_left_joint" type="prismatic">
        <parent link="gripper_base"/>
        <child link="gripper_left_link"/>
        <origin xyz="0.0817 0.021 0.0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit velocity="4.8" effort="1000" lower="-0.010" upper="0.019" />
        <dynamics damping="0.1"/>
    </joint>

    <link name="gripper_left_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/gripper_left_palm.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/gripper_left_palm.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.020" x="0.05" y="0.01" z="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="gripper_right_joint" type="prismatic">
        <parent link="gripper_base"/>
        <child link="gripper_right_link"/>
        <origin xyz="0.0817 -0.021 0" rpy="0 0 0"/>
        <axis xyz="0 -1 0"/>
        <limit velocity="4.8" effort="1000" lower="-0.010" upper="0.019" />
        <dynamics damping="0.1"/>
        <mimic joint="gripper_left_joint" multiplier="1"/>
    </joint>

    <link name="gripper_right_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/gripper_right_palm.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/gripper_right_palm.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.020" x="0.05" y="0.01" z="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="end_effector_joint" type="fixed">
        <parent link="gripper_base"/>
        <child link="end_effector_link"/>
        <origin xyz="0.126 0.0 0.0" rpy="0 0 0"/>
    </joint>

    <link name="end_effector_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01" />
            </geometry>
            <material name="red">
                <color rgba="1.0 0.0 0.0 1"/>
            </material>
        </visual>
    </link>
    
    <joint name="D405_to_gripper_base" type="fixed">
        <parent link="gripper_base"/>
        <child link="D405"/>
        <origin xyz="0.03 0 0.07" rpy="0 0 0"/>
    </joint>

    <link name="D405">
        <visual>
            <origin xyz="0 0 0 " rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/D405.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="light_grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0 " rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/D405.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision> 
        <xacro:inertial_box mass="0.06" x="0.023" y="0.042" z="0.042">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

</robot>
